### PR TITLE
React + Express Example

### PR DESCRIPTION
**Pull request by adrianmcli**
I created an example React project for myself: https://github.com/adrianmcli/meta-auth-example

It uses a barebones, non-ejected, Create-React-App boilerplate (which is the standard in the industry).

I figured you might want this in your repo as well. It certainly would make things easier for people who are already familiar with React.

`App.js` has the most important stuff. I will also highlight the important points here:

## Step 1 — Get the challenge

Assuming that `web3` and `accounts` has been loaded into local component state, this is how you request the challenge from the server and then save the response:

```js
getChallenge = async () => {
  const { accounts } = this.state;
  const res = await fetch(
    `http://localhost:3001/auth/${accounts[0].toLowerCase()}`
  );
  this.setState({ challenge: await res.json() });
};
```

## Step 2 — Ask user to sign the challenge

This will ask the user to sign the challenge in order for him to prove he is who he says he is. It should cause MetaMask to pop-up.

```js
signChallenge = async () => {
  const { web3, challenge, accounts } = this.state;
  web3.currentProvider.sendAsync(
    {
      method: "eth_signTypedData",
      params: [challenge, accounts[0]],
      from: accounts[0]
    },
    (error, res) => {
      if (error) return console.error(error);
      this.setState({ signature: res.result });
    }
  );
};
```

## Step 3 — Send the signed challenge to the server for verification

Depending on the response of the server, we will know whether or not the user's identity has been authenticated.

```js
verifySignature = async () => {
  const { challenge, signature, accounts } = this.state;
  const res = await fetch(
    `http://localhost:3001/auth/${challenge[1].value}/${signature}`
  );
  const recovered = await res.text();
  if (res.status === 200 && recovered === accounts[0].toLowerCase()) {
    console.log("Signature verified");
  } else {
    console.log("Signature not verified");
  }
};
```

### CODE REVIEW

**Comment by tenthirtyone** [comment]
I apologize for taking so long. I've been working on another project and plan to roll this one into its organization. 

We're going to be moving to Heritage-Aero and this will be part of Airbus' Heritage project (www.heritage.aero).

I will review before/after the move.

**Comment by adrianmcli** [comment]
@tenthirtyone Sounds good!

I'm actually on the Truffle team now, thanks for giving the talk at our conference earlier this month. Too bad we didn't get a chance to talk in-person.

**Comment by tenthirtyone** [comment]
@adrianmcli That's AWESOME. Congratulations!
 
I still owe Tim an email. Hopefully we can cross paths soon.

**Comment by adrianmcli** [comment]
Thanks!

But speaking of which, I need to update this PR to work with EIP-1102 and the new way MetaMask injects a provider (due November 2). Maybe I'll update this on the weekend.

**Comment by tenthirtyone** [comment]
Ehhhh green buttoned!

**Pull request merged**
